[theme]
primaryColor = "#4b6fff"
backgroundColor = "#f5f7f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "warning"

[server]
headless = true
port = 8501
enableXsrfProtection = true
maxUploadSize = 200
enableCORS = true

[browser]
gatherUsageStats = false
